services:
  postgres:
    image: postgres:16
    container_name: superhero-postgres
    environment:
      POSTGRES_USER: super_user
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: superhero_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
